"""
Local LLM Service — Direct HTTP client for the local GGUF model.
Calls localhost:8011/v1/chat/completions (llama_cpp.server OpenAI-compatible API).
No Haystack, no external APIs, no downloads. Just fast local inference.
"""
import logging
import requests
import time
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

LLM_PORT = 8011
LLM_BASE_URL = f"http://localhost:{LLM_PORT}"
CHAT_ENDPOINT = f"{LLM_BASE_URL}/v1/chat/completions"

# Retry config
MAX_RETRIES = 3
RETRY_DELAY = 2  # seconds
TIMEOUT = 120  # seconds


def is_model_ready() -> bool:
    """Check if local GGUF model server is running and ready."""
    try:
        resp = requests.get(f"{LLM_BASE_URL}/v1/models", timeout=3)
        return resp.status_code == 200
    except Exception:
        return False


def get_model_info() -> dict:
    """Get info about the loaded model."""
    try:
        resp = requests.get(f"{LLM_BASE_URL}/v1/models", timeout=3)
        if resp.status_code == 200:
            data = resp.json().get("data", [])
            if data:
                return {"id": data[0]["id"], "ready": True}
        return {"id": "unknown", "ready": False}
    except Exception:
        return {"id": "none", "ready": False}


def chat(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    max_tokens: int = 512,
) -> str:
    """
    Send a chat completion request to the local GGUF model.
    
    Args:
        messages: List of {"role": "system"|"user"|"assistant", "content": str}
        temperature: Sampling temperature (0.0-1.0)
        max_tokens: Maximum response tokens
    
    Returns:
        The model's text response, or a fallback error message.
    """
    payload = {
        "model": "local-gguf",  # ignored by llama_cpp, but required by API
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(
                CHAT_ENDPOINT,
                json=payload,
                timeout=TIMEOUT,
            )
            
            if resp.status_code == 200:
                data = resp.json()
                choices = data.get("choices", [])
                if choices:
                    content = choices[0].get("message", {}).get("content", "")
                    if content.strip():
                        return content.strip()
                    return "I received your question but couldn't generate a meaningful response. Please try rephrasing."
                return "No response generated by the model."
            
            last_error = f"HTTP {resp.status_code}: {resp.text[:200]}"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} failed: {last_error}")
            
        except requests.exceptions.Timeout:
            last_error = "Request timed out"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} timed out")
        except requests.exceptions.ConnectionError:
            last_error = "Cannot connect to model server"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} connection refused")
        except Exception as e:
            last_error = str(e)
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} error: {e}")

        if attempt < MAX_RETRIES:
            time.sleep(RETRY_DELAY)

    logger.error(f"All {MAX_RETRIES} LLM attempts failed. Last error: {last_error}")
    return "⚠️ Model temporarily unavailable. Please try again in a moment."


def guide_chat(query: str, platform_knowledge: str) -> str:
    """
    Guide Mode: Answer user questions about the OmniRAG platform.
    Uses platform knowledge as system prompt.
    """
    messages = [
        {
            "role": "system",
            "content": (
                f"{platform_knowledge}\n\n"
                "Answer the user's question helpfully and concisely based on your knowledge of OmniRAG. "
                "If asked about building a RAG, guide them step by step. Be practical and encouraging."
            ),
        },
        {"role": "user", "content": query},
    ]
    return chat(messages, temperature=0.3, max_tokens=512)


def test_chat(query: str, context_docs: str) -> str:
    """
    Test Mode: Answer questions using retrieved document context.
    Documents are passed as context in the system prompt.
    """
    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful AI assistant. Answer the question based ONLY on the provided context. "
                "If the context doesn't contain the answer, say so honestly.\n\n"
                f"Context:\n{context_docs}"
            ),
        },
        {"role": "user", "content": query},
    ]
    return chat(messages, temperature=0.3, max_tokens=512)
