"""
Local LLM Service — Direct HTTP client for the local GGUF model.
Calls localhost:8010/v1/chat/completions (llama_cpp.server OpenAI-compatible API).
No Haystack, no external APIs, no downloads. Just fast local inference.
"""
import logging
import httpx
import asyncio
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

LLM_PORT = 8010
LLM_BASE_URL = f"http://localhost:{LLM_PORT}"
CHAT_ENDPOINT = f"{LLM_BASE_URL}/v1/chat/completions"

# Retry config
MAX_RETRIES = 2
RETRY_DELAY = 1  # seconds
TIMEOUT = 60.0  # seconds


def is_model_ready() -> bool:
    """Check if local GGUF model server is running and ready. By default True since it is mounted in FastAPI."""
    return True

def get_model_info() -> dict:
    """Get info about the loaded model. Hardcoded for now since it is mounted."""
    return {"id": "local-gguf", "ready": True}


async def chat(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    max_tokens: int = 512,
) -> str:
    """
    Send a chat completion request to the local GGUF model asynchronously.
    """
    payload = {
        "model": "local-gguf",  # ignored by llama_cpp, but required by API
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }

    last_error = None
    async with httpx.AsyncClient(timeout=TIMEOUT) as client:
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                resp = await client.post(CHAT_ENDPOINT, json=payload)
                
                if resp.status_code == 200:
                    data = resp.json()
                    choices = data.get("choices", [])
                    if choices:
                        content = choices[0].get("message", {}).get("content", "")
                        if content.strip():
                            return content.strip()
                        return "I received your question but couldn't generate a meaningful response. Please try rephrasing."
                    return "No response generated by the model."
                
                last_error = f"HTTP {resp.status_code}: {resp.text[:200]}"
                logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} failed: {last_error}")
                
            except httpx.TimeoutException:
                last_error = "Request timed out"
                logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} timed out")
            except httpx.RequestError as e:
                last_error = "Cannot connect to model server"
                logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} connection refused: {e}")
            except Exception as e:
                last_error = str(e)
                logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} error: {e}")

            if attempt < MAX_RETRIES:
                await asyncio.sleep(RETRY_DELAY)

    logger.error(f"All {MAX_RETRIES} LLM attempts failed. Last error: {last_error}")
    return "⚠️ Model temporarily unavailable. Please try again in a moment."


async def chat_stream(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    max_tokens: int = 512,
):
    """
    Asynchronous streaming version of chat(). Yields text chunks as they arrive.
    """
    payload = {
        "model": "local-gguf",
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": True,
    }

    try:
        async with httpx.AsyncClient(timeout=TIMEOUT) as client:
            async with client.stream("POST", CHAT_ENDPOINT, json=payload) as resp:
                if resp.status_code != 200:
                    error_text = await resp.aread()
                    yield f"⚠️ Error {resp.status_code}: {error_text.decode('utf-8')[:100]}"
                    return

                import json
                async for line in resp.aiter_lines():
                    if line:
                        if line.startswith('data: '):
                            data_str = line[6:]
                            if data_str.strip() == '[DONE]':
                                break
                            try:
                                data = json.loads(data_str)
                                chunk = data.get("choices", [{}])[0].get("delta", {}).get("content", "")
                                if chunk:
                                    yield chunk
                            except Exception:
                                continue
    except Exception as e:
        logger.error(f"Streaming error: {e}")
        yield "⚠️ Connection lost. Please try again."


async def guide_chat(query: str, platform_knowledge: str) -> str:
    """Guide Mode: Answer questions about OmniRAG."""
    messages = [
        {"role": "system", "content": f"{platform_knowledge}\\n\\nAnswer helpfully and concisely."},
        {"role": "user", "content": query},
    ]
    return await chat(messages)


async def guide_chat_stream(query: str, platform_knowledge: str):
    """Streaming Guide Mode."""
    messages = [
        {"role": "system", "content": f"{platform_knowledge}\\n\\nAnswer helpfully and concisely."},
        {"role": "user", "content": query},
    ]
    async for chunk in chat_stream(messages):
        yield chunk


async def test_chat(query: str, context_docs: str) -> str:
    """Test Mode: Answer questions using retrieved context."""
    messages = [
        {"role": "system", "content": f"Context:\\n{context_docs}\\n\\nAnswer based ONLY on context."},
        {"role": "user", "content": query},
    ]
    return await chat(messages)


async def test_chat_stream(query: str, context_docs: str):
    """Streaming Test Mode."""
    messages = [
        {"role": "system", "content": f"Context:\\n{context_docs}\\n\\nAnswer based ONLY on context."},
        {"role": "user", "content": query},
    ]
    async for chunk in chat_stream(messages):
        yield chunk
