"""
Local LLM Service — Direct HTTP client for the local GGUF model.
Calls localhost:8011/v1/chat/completions (llama_cpp.server OpenAI-compatible API).
No Haystack, no external APIs, no downloads. Just fast local inference.
"""
import logging
import requests
import time
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)

LLM_PORT = 8010
LLM_BASE_URL = f"http://localhost:{LLM_PORT}"
CHAT_ENDPOINT = f"{LLM_BASE_URL}/v1/chat/completions"

# Retry config
MAX_RETRIES = 2
RETRY_DELAY = 1  # seconds
TIMEOUT = 60  # seconds


def is_model_ready() -> bool:
    """Check if local GGUF model server is running and ready. By default True since it is mounted in FastAPI."""
    return True

def get_model_info() -> dict:
    """Get info about the loaded model. Hardcoded for now since it is mounted."""
    return {"id": "local-gguf", "ready": True}


def chat(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    max_tokens: int = 512,
) -> str:
    """
    Send a chat completion request to the local GGUF model.
    
    Args:
        messages: List of {"role": "system"|"user"|"assistant", "content": str}
        temperature: Sampling temperature (0.0-1.0)
        max_tokens: Maximum response tokens
    
    Returns:
        The model's text response, or a fallback error message.
    """
    payload = {
        "model": "local-gguf",  # ignored by llama_cpp, but required by API
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": False,
    }

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(
                CHAT_ENDPOINT,
                json=payload,
                timeout=TIMEOUT,
            )
            
            if resp.status_code == 200:
                data = resp.json()
                choices = data.get("choices", [])
                if choices:
                    content = choices[0].get("message", {}).get("content", "")
                    if content.strip():
                        return content.strip()
                    return "I received your question but couldn't generate a meaningful response. Please try rephrasing."
                return "No response generated by the model."
            
            last_error = f"HTTP {resp.status_code}: {resp.text[:200]}"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} failed: {last_error}")
            
        except requests.exceptions.Timeout:
            last_error = "Request timed out"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} timed out")
        except requests.exceptions.ConnectionError:
            last_error = "Cannot connect to model server"
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} connection refused")
        except Exception as e:
            last_error = str(e)
            logger.warning(f"LLM attempt {attempt}/{MAX_RETRIES} error: {e}")

        if attempt < MAX_RETRIES:
            time.sleep(RETRY_DELAY)

    logger.error(f"All {MAX_RETRIES} LLM attempts failed. Last error: {last_error}")
    return "⚠️ Model temporarily unavailable. Please try again in a moment."


def chat_stream(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    max_tokens: int = 512,
):
    """
    Streaming version of chat(). Yields text chunks as they arrive.
    """
    payload = {
        "model": "local-gguf",
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "stream": True,
    }

    try:
        # Use a fresh request for streaming
        resp = requests.post(
            CHAT_ENDPOINT,
            json=payload,
            timeout=TIMEOUT,
            stream=True
        )
        
        if resp.status_code != 200:
            yield f"⚠️ Error {resp.status_code}: {resp.text[:100]}"
            return

        import json
        for line in resp.iter_lines():
            if line:
                decoded_line = line.decode('utf-8')
                if decoded_line.startswith('data: '):
                    data_str = decoded_line[6:]
                    if data_str.strip() == '[DONE]':
                        break
                    try:
                        data = json.loads(data_str)
                        chunk = data.get("choices", [{}])[0].get("delta", {}).get("content", "")
                        if chunk:
                            yield chunk
                    except Exception:
                        continue
    except Exception as e:
        logger.error(f"Streaming error: {e}")
        yield "⚠️ Connection lost. Please try again."


def guide_chat(query: str, platform_knowledge: str) -> str:
    """Guide Mode: Answer questions about OmniRAG."""
    messages = [
        {"role": "system", "content": f"{platform_knowledge}\n\nAnswer helpfully and concisely."},
        {"role": "user", "content": query},
    ]
    return chat(messages)


def guide_chat_stream(query: str, platform_knowledge: str):
    """Streaming Guide Mode."""
    messages = [
        {"role": "system", "content": f"{platform_knowledge}\n\nAnswer helpfully and concisely."},
        {"role": "user", "content": query},
    ]
    return chat_stream(messages)


def test_chat(query: str, context_docs: str) -> str:
    """Test Mode: Answer questions using retrieved context."""
    messages = [
        {"role": "system", "content": f"Context:\n{context_docs}\n\nAnswer based ONLY on context."},
        {"role": "user", "content": query},
    ]
    return chat(messages)


def test_chat_stream(query: str, context_docs: str):
    """Streaming Test Mode."""
    messages = [
        {"role": "system", "content": f"Context:\n{context_docs}\n\nAnswer based ONLY on context."},
        {"role": "user", "content": query},
    ]
    return chat_stream(messages)
